### PR TITLE
chouaib-node.js-homework-w1

### PR DESCRIPTION
**Pull request by chouaib-at**

### CODE REVIEW

**Comment by namighadri** [comment]
Hi chouaib,

**Comment by namighadri** [comment]
Hi chouaib,

I see that you are using node-fetch but, it is not included in package.json , maybe you did not push the last configuration  and if could put the project folder under homework folder,

**Comment by chouaib-at** [comment]
Hello node fetch is for week 2 not week 1

**Comment by chouaib-at** [comment]
And I will fix the first issue that you sent to me about the console log in week 1 as Soon as possible

**Comment by namighadri** [comment]
I can't find your w1 , it seems that it is closed

**Comment by chouaib-at** [comment]
Yes I had an issue I couldn’t make a new pull requests i had to close the
w1 to make a new pull request

**Comment by chouaib-at** [comment]
https://github.com/HackYourHomework/Node.js-class44/pull/17/commits/1647959a92d79f85b25a6fdae22aceb8290db67f

**Comment by robvk** [comment]
The problem is that you are not using branches as you are asked to which is why you can't have 2 open. Make a new branch for week 1 stuff and then fix it and send @namighadri a link to this new pull request

**Comment by chouaib-at** [comment]
Ok, I will do that.

**Comment by chouaib-at** [comment]
can you check please the last update :

https://github.com/HackYourHomework/Node.js-class44/pull/31
https://github.com/HackYourHomework/Node.js-class44/pull/30

**Pull request closed without merging**
